### ISSUE TITLE
Assembly Scanning is broken?

### ISSUE THREAD

**Issue by endeffects** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#73]
With the latest version the assembly scanning does not work for referenced assemblies anymore. I have to specifiy each assembly by my own. Is this really a good choice?

**Comment by endeffects** [comment]
Ah i saw your obsolete hint and using AppDomain.CurrentDomain.GetAssemblies() works for me.
But i think you should update the readme.md.

**Comment by smann004** [comment]
> Ah i saw your obsolete hint and using AppDomain.CurrentDomain.GetAssemblies() works for me.
> But i think you should update the readme.md.

I too hope for some updated and or expanded code samples in either the readme.md or elsewhere. I have struggled to figure out how best to implement MediatR with Asp.Net core 2.2. I have switched from Castle.Windsor DI to Microsoft and still do not have working code.

**Comment by jbogard** [comment]
What in the readme is incorrect? It shows passing in the assembly or type
where you can scan for handlers.

**Comment by smann004** [comment]
I don't think anything in the readme is incorrect but the issue for me is that I don't know for what solution the code fits. I am trying to translate the Ping/Pong sample from https://github.com/jbogard/MediatR/tree/master/samples
In to a asp.net core 2.2 solution and have not yet been successful. When I figure out what I'm doing wrong I will share.
The MediatR samples project mentioned above
has a staggering amount of code with sample projects for every DI container in existence. The problem is that I can't find an asp.net core 2.2 solution to use as a reference. I almost feel like I should remove the dependency injection extension so I see how the container is being constructed.
